### ISSUE TITLE
Exception encountered, of type "BadMethodCallException"

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#102]
Occured to me around Sept 16, 18:55:55 (UTC+9) for me while login.

+

Reported by cropro around 10:09 UTC while logout/login.

**Comment by revi** [comment]
Please note that the issue title is only thing user get, no any information required for debugging.

**Comment by Southparkfan** [comment]
Fixed in 5039dd5c7face67c7a8b7de2018cf498e97262c8.
