### ISSUE TITLE
Endless job queue for allthetropeswiki

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#114]
It looks like the job queue for allthetropeswiki never goes to zero, even if you run 500 jobs (I did 800 or something), it keeps staying above 1500.

**Comment by labster** [comment]
Yeah, I remember something similar happening on Orain.  For some reason, the job queue never shows all the jobs available, or the jobs spawn more jobs.  It seems to like to stay in the 1200-1600 range.

**Comment by Southparkfan** [comment]
Seems fixed to me.
