### ISSUE TITLE
Redesign missing wiki page

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#118]
The current version is ugly.

**Comment by revi** [comment]
Maybe with a vector skin design, letting the user that wiki doesn't exist and telling user they can request the wiki?

**Comment by Wynter** [comment]
Should this be closed per #128?

**Comment by NDKilla** [comment]
@Wynter  I still feel like it could use some pretty css or a background or something.

Possibly also a Powered by MediaWiki logo in the bottom left, and an nginx one if it exists? 

I think it looks better but not great

**Comment by Southparkfan** [comment]
Done?
