### ISSUE TITLE
db crashed on search

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#119]
A database query error has occurred. This may indicate a bug in the software.

Function: SearchMySQL::searchInternal
Error: 145 Table './metawiki/searchindex' is marked as crashed and should be repaired (185.52.1.77)

**Comment by Wynter** [comment]
What URL were you trying to access? I'm not getting any errors on Meta or ReviWiki.

**Comment by revi** [comment]
Search nonexisting pages on meta. It is already known to sysadmins since yesterday. Was solved then but reoccuring.

ps. RCBot dead.

**Comment by Wynter** [comment]
OK, I'm getting the error too (only on Meta).

**Comment by revi** [comment]
Well you don't have read access on reviwiki hence you won't see anything beyond mainpage there.

**Comment by Wynter** [comment]
I tried it on reviwiki and some other public wikis, and I didn't have any problems anywhere except on metawiki. However, Robkelk on Request Features says it's now happening on poserdazfreebieswiki too. I've confirmed that this is the case.

**Comment by Wynter** [comment]
Confirmed on 8stationwiki as well.

Wikis with the issue (that I've confirmed):
* metawiki
* poserdazfreebieswiki
* 8stationwiki

**Comment by JohnFLewis** [comment]
Aware.

**Comment by JohnFLewis** [comment]
Confirmed cause is OOM's caused by the ATTwiki import by SPF.

**Comment by revi** [comment]
This is happening again, on meta.

**Comment by JohnFLewis** [comment]
Resolved again through a restart.

**Comment by Reception123** [comment]
Happening again on meta
