### ISSUE TITLE
permanentfuturelabwiki import

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#140]
Import text and add custom domain (ssl cert emailed). Will do today.

**Comment by Southparkfan** [comment]
Scheduled this for tomorrow.

**Comment by jurjendevries** [comment]
I just changed DNS for permanentfuturelab.wiki domain to ns1.miraheze.org , ns2.miraheze.org & ns3.miraheze.org cc https://part-up.com/partups/moving-wiki-hosting-Gp553oWNiJ6hcHCY3/updates/rMLJayjw5NqAsnFZt

**Comment by Southparkfan** [comment]
Custom domain works now. I'm now doing the text import.

**Comment by revi** [comment]
```importDump.php``` was ran, ```rebuildrecentchange.php``` was also ran. Any double-checks or did I miss something?

**Comment by revi** [comment]
GTG from @Southparkfan via IRC, so officialy done.
