### ISSUE TITLE
poserdazfreebieswiki import.

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#141]
Import the images of this wiki. Should be done today.

**Comment by Southparkfan** [comment]
Assigned to revi. Will email him the images.

**Comment by Southparkfan** [comment]
@revi: If the import is not done before 17:30 CEST tomorrow, then I'll do it.

**Comment by revi** [comment]
No worries, will do today afternoon.

**Comment by revi** [comment]
```/home/revi/images/1.zip``` (AKA ```poserdazfreebies-images-robkelk.zip```) is corrupted, when I downloaded it.

**Comment by revi** [comment]
Batch 1 skipped/failed images
```
skipped
----
NFC.png (exists)
failed
----
MMTubetop-bikiniForV4A4.png
Shelia_hair_V4.png
Sara_2.png
Nene_Hair_for_V4A4.png
TPrea_hair_V4.png
```
Batch 2 was cleanly done.
Batch 3 failed images
```
Eroko.png
AlisAngela.png
ChgnonHair.png
```

**Comment by JohnFLewis** [comment]
Updates?

**Comment by revi** [comment]
All done except errors. No retry since then. Will try in a few hours....

**Comment by revi** [comment]
All files are imported without error by now. Closing.
