### ISSUE TITLE
Backup process

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#143]
We need to have it. We should be aware of the lessons of Orain.

Problem is how.

**Comment by stefek99** [comment]
+1

I didn't know about Orain case: http://drunkardswalkforums.yuku.com/reply/132507/All-The-Tropes-Wiki-Project-Part-V#reply-132507

> I have some horrible news to report: Orain has been epically compromised, as in, raped to an absurd degree.
> We were compromised at the server level, and all databases have been wiped. As in  sudo rm -rfed level wiped.

I would really like to put my trust in you and start investing into creating content on my wiki.

Knowing that there is **reliable and documented process** will allow me to have much better sleep at night.

Some criteria worth considering:
* no single server
* no single person
* do we want to backup assets too? (each can be up to 100MB)

Services that are popular:
* Amazon Glacier
* Tarsnap

Ideally - I would like the most recent backup to be hosted publicly so I can have it on my server / Dropbox / GoogleDrive / external HDD.

**Comment by JohnFLewis** [comment]
I really do want backups yet I also want it to be universal process for public and *private* information. This limits my willingness to fund to a service with great disk space only.

It will be a single server regardless as distribute content twice (in theory, three times) is a waste of money in my opinion. There won't be a single person - there is infact no single person for anything unless legal or government restrictions apply.

**Comment by Arcane21** [comment]
You could always donate the backups to archive.org.

**Comment by Southparkfan** [comment]
https://meta.miraheze.org/wiki/User:Southparkfan/BackupsDraft

**Comment by Arcane21** [comment]
You guys might wish to get in touch with the WikiTeam for additional assistance with wiki archival services.

**Comment by revi** [comment]
Wikiteam backup will make some loads on our server since they access all live version of a wiki via API to make a dump. Dump via Mediawiki-provided php script will be better.

Also, we have to think about private informations. We cannot have it on archive.org, can we?

**Comment by Arcane21** [comment]
Points noted, revi. Archive.org could serve as an XML dump backup hub, at least, which would be a good alternative for those who merely want the wiki content minus any private data.

**Comment by revi** [comment]
I already uploaded [some](https://archive.org/details/20150927-genwiki-fullXml) [dumps](https://archive.org/details/20150927-test.miraheze.org-full.xml) to archive.org when requested by wiki owners. I will do the same when dump is requested by the users (and there is no established process)

**Comment by Arcane21** [comment]
With that in mind, I was wondering if you wouldn't mind uploading, if nothing else, current revision dumps of ATT to archive.org at least once a month in  (zipped) XML format. Since we use the CC BY SA license, this is sufficient for copyright reasons as opposed to GDFL, which requires full revision histories. This is also for easier portability in case someone wishes to mirror us (a practice I and out other staff members encourage) minus worrying about spreading around private data like with SQL dumps (those dumps I expect will be kept by Miraheze for their own archival purposes).

Full revision dumps would be nice, but a monthly backup of our current revisions would be better than nothing.

As for images, once our current issues are resolved with that, a backup of those every three to six months uploaded to archive.org would also be greatly preferred.

**Comment by jurjendevries** [comment]
I tried Wikiteam before with the command:

python dumpgenerator.py --index=permanentfuturelab.wiki/wiki/Permanent_Future_La.. --api=permanentfuturelab.wiki/w/api.php --delay=5 --xml --images

But that generates an error:
Checking API... permanentfuturelab.wiki/w/api.php Connection error: hostname 'permanentfuturelab.wiki' doesn't match either of '*.miraheze.org', 'miraheze.org' .

Soutparkfan said it may be a problem with SSL SNI. He will try to look for a solution.

**Comment by Reception123** [comment]
@Southparkfan @revi This is important. We should think when we do the next backup? Will we do one before 1.26?

**Comment by Arcane21** [comment]
Already tried out MW 1.26. It has no earth shattering DB changes, so downgrading back won't be too hard, but a backup could not hurt.


________________________________

**Comment by NDKilla** [comment]
Any updates on this? I think some backups are currently stored on various servers but they're not publicly accessible and the process is not done automatically.

**Comment by JohnFLewis** [comment]
This is done.
