### ISSUE TITLE
Import izanagiwiki

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#148]
Requestd on [[meta:SN]]. I don't have XML file yet.

**Comment by revi** [comment]
Scheduled for tomorrow.

@Southparkfan this is your reminder to send dump to ```/home/revi/dumps```. :-)

**Comment by Southparkfan** [comment]
Dump provided in /home/revi.

**Comment by revi** [comment]
Imported. Closing - if you notice errors/problems, feel free to slap me.
