### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#155]
Since now I am getting 502 Bad Gateway when I try to access any wiki, @Southparkfan @JohnFLewis

**Comment by revi** [comment]
Aware.

**Comment by revi** [comment]
![](http://puu.sh/kpzOk/d272131a97.png)

The graph says something happened around 01:20 UTC and then users started to get 502.

**Comment by revi** [comment]
[SAL](https://meta.miraheze.org/w/index.php?title=Tech%3AServer_admin_log&type=revision&diff=2060&oldid=2006)

```04:33 revi: restarted HHVM, was generating 502```

Back online.

**Comment by revi** [comment]
I will leave analysis on cause to @JohnFLewis and @Southparkfan.

**Comment by Reception123** [comment]
Bad gateway still happens, and is happening now. Would re-open the issue.

**Comment by Southparkfan** [comment]
root@mw1:~# uptime
 10:45:00 up  3:44,  2 users,  load average: 0.12, 0.12, 0.08

For an unknown reason mw1 was rebooted. After the reboot Apache got started (which took precedence over nginx), thus nginx was not able to restart itself which resulted in the 503 errors (Varnish connects to 8080, stunnel connects to :443 on mw1, but Apache does not listen on :443, so Varnish threw 503 errors).

I've removed apache2 from mw1. Why mw1 got rebooted is still a mystery. misc1 and db1 (which are on the same node as mw1) have not been rebooted, so it was no emergency reboot, node failure or maintenance by RamNode.

@JohnFLewis I kindly invite you to look why a reboot occurred. Debian 8 logging is, imho, annoying I guess (messages, kern.log, dmesg, syslog and such do not contain useful messages at all).
