### ISSUE TITLE
Images on ATT do not seem to have been imported properly

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#160]
Many images that should have imported with the initial dump claim to be registered in the file lists but there are no pictures. The image import process may need to be run again to remedy this.

**Comment by Southparkfan** [comment]
Seems fine to me? https://allthetropes.miraheze.org/w/index.php?title=Special:Log/upload&offset=&limit=5000&type=upload&user= Perhaps I need to import the numeric folder too, but this torrent is over a year old. Images that were uploaded after the torrent was uploaded, are not in the torrent (but they have an image page because the db backup is much never), so I can't import them obviously.

**Comment by Arcane21** [comment]
The numeric ones are the missing images.

**Comment by Southparkfan** [comment]
I'll import them.

**Comment by Southparkfan** [comment]
@Arcane21: imported. Please close this issue if this looks good to you.

**Comment by Arcane21** [comment]
Looks better, but some of the images from the non numeric folder still look messed up. You might want to reimport them as well just in case any were missed, flush the cache, and then I'll be able to say for sure whether this can be closed.

**Comment by Southparkfan** [comment]
root@mw1:~# cat output.log | grep imported
200px-Missile_S3_monte▒_en_position_verticale_Musee_du_Bourget_P1010455.jpg could not be imported; a valid title cannot be produced

**Comment by Arcane21** [comment]
Tell it to ignore that file and any others that fail, some of the names were parsed very strangely and a few files failed on Orain too.

**Comment by Southparkfan** [comment]
Can you please give me a list of images (if the full list is too difficult to generate, give me a few) you need? During some move/copy work some got lost (I still have an untouched folder on my pc, though, so it's no problem to re-upload) I guess.

**Comment by Arcane21** [comment]
Not really. The pictures say they 'copied", but the thumbnails aren't there and the source files are missing despite claiming they are there.

**Comment by Southparkfan** [comment]
Please give me a few examples?

**Comment by Arcane21** [comment]
https://allthetropes.miraheze.org/wiki/File:Star_wars_emperor_throne_room_7256.jpg

https://allthetropes.miraheze.org/wiki/File:Precocious1_8271.jpg

https://allthetropes.miraheze.org/wiki/File:Batman-bin-suparman.jpg

**Comment by Southparkfan** [comment]
Exactly what I thought. The pages were imported with the SQL import, but the files were never uploaded. I'll write a temp script to find more of those images, so I can import them.

**Comment by Arcane21** [comment]
Understood. All the other stuff that is a legit red link is stuff not in the dump we provided, but we've got that part covered.

**Comment by Arcane21** [comment]
Need an update on the image reimport.

**Comment by Southparkfan** [comment]
@Arcane21: is everything covered now?

**Comment by Arcane21** [comment]
If you redid the import and we have all the images we're supposed to, then yes.

**Comment by Southparkfan** [comment]
https://allthetropes.miraheze.org/wiki/User:Southparkfan/MissingImages

Looks like I need to import more than 20k images. Will do.

**Comment by Arcane21** [comment]
The new image dump went horribly wrong:

**Comment by Southparkfan** [comment]
That's not the case:

I deleted all image pages that had no associated file with them on the server, so importImages.php can import them.

It looks like that deleting image pages caused MediaWiki to show the InstantCommons' version of those images..

I'll work on it when I have time today.

**Comment by Arcane21** [comment]
I see, that make sense, thanks for the heads up.


________________________________

**Comment by Southparkfan** [comment]
@Arcane21 are ALL images in the torrent from TVTropes? If yes, can I use the following template when creating each image page:
{{tvtimageimport|http://static.tvtropes.org/pmwiki/pub/images/{{urlencode:{{lc:{{subst:PAGENAMEE}}}}}}}}

{{TVT-CC-BY-SA-image}}

**Comment by Arcane21** [comment]
Yes.


________________________________

**Comment by Southparkfan** [comment]
Should be:

{{tvtimageimport|http://static.tvtropes.org/pmwiki/pub/images/{{urlencode:{{lcfirst:{{subst:PAGENAMEE}}}}}}}}

{{TVT-CC-BY-SA-image}}

**Comment by Southparkfan** [comment]
@Arcane21:

Import ongoing: https://allthetropes.miraheze.org/wiki/Special:Log/upload

**Comment by labster** [comment]
@Arcane21 do we have enough of the images now that this is closable?

**Comment by Arcane21** [comment]
Close enough.


________________________________

**Comment by labster** [comment]
Well, then, in my first use of github admin powers :clap:, I'll go ahead and close this.
