### ISSUE TITLE
Can't rebuild LC on mw1

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#161]
ndkilla@mw1:/srv/mediawiki/w/maintenance$ php rebuildLocalisationCache.php --wiki extloadwiki
Rebuilding ab...
PHP Warning:  dba_open(/srv/mediawiki/w/cache/l10n/l10n_cache-ab.cdb.tmp.1935890328): failed to open stream: Permission denied in /srv/mediawiki/w/vendor/wikimedia/cdb/src/Writer/DBA.php on line 38
Set $wgShowExceptionDetails = true; in LocalSettings.php to show detailed debugging information.

I didn't enable ShowExceptionDetails but based on previous experiences I'm assuming this is because I didn't sudo the command.
When I tried to sudo the command, I can't. Soo.. I reverted the commit enabling SyntaxHighlight_GeSHi on extloadwiki (why I wanted to rebuild LC) and am opening this issue.

Worth noting I tried forcing the rebuild didn't help.

**Comment by NDKilla** [comment]
@Southparkfan @JohnFLewis :p I feel like an idiot atm.
I force ran puppet again and confirmed that the extension wasn't being loaded on extloadwiki so that this wouldn't cause any issues. 

I'm actually going to get ready for bed soon.. sorry for this

**Comment by revi** [comment]
Well, have you tried ```sudo -u www-data (command)```?

**Comment by JohnFLewis** [comment]
Access is delegated. As revi said, please sudo -u www-data.
