### ISSUE TITLE
Flow for spiral.wiki

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#17]
It would be great to have Flow for spiralwiki, for everybody and everything. Existing discussion pages should be migrated or archived.

**Comment by JohnFLewis** [comment]
Will do.

**Comment by Southparkfan** [comment]
Talk pages converted and Flow enabled by default.

**Comment by quimgil** [comment]
After yesterday's re-import, Flow needs to be re-enabled properly. 

The Flow bot seems to have moved the wikitext discussions (good) but the new Flow pages are not there (bad). For instance, click "Discussion"at https://spiral.wiki/wiki/Happiness_for_everyone
