### ISSUE TITLE
Need our Trope Workshop working, have no idea what I'm doing, request staff assitance

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#171]
I have no idea what I'm doing or how to submit it correctly to Miraheze, and I'm asking someone to please add it in Miraheze kosher format ASAP, as we really need this working, else our Trope Workshop space is horribly broken. I have a lot of other things I need to get done ASAP,. so I cannot unfortunately take the time to learn what it is I need to do, but my wiki community really needs this working soon.

Here was our config from Orain:

#Custom Namespaces
define( "NS_TROPEWORKSHOP", 520 );
define( "NS_TROPEWORKSHOP_TALK", 521 );

$wgExtraNamespaces[NS_TROPEWORKSHOP] = "Trope Workshop";
$wgExtraNamespaces[NS_TROPEWORKSHOP_TALK] = "Trope Workshop talk";   // underscore required
$wgNamespacesWithSubpages[NS_TROPEWORKSHOP] = true;            //subpages enabled for the namespace

#Namespace Aliases for All The Tropes
$wgNamespaceAliases['ATT'] = NS_PROJECT;
$wgNamespaceAliases['ATT_talk'] = NS_PROJECT_TALK;

#Namespace Aliases for Trope Workshop
$wgNamespaceAliases['YKTTW' ] = NS_TROPEWORKSHOP;
$wgNamespaceAliases['YKTTW_talk'] = NS_TROPEWORKSHOP_TALK;

**Comment by NDKilla** [comment]
Done in [commit ba63244](https://github.com/miraheze/mw-config/commit/ba63244a6213f12c34374f878c0522c4d320c930)
