### ISSUE TITLE
Need all pages from here repaired, DB issue

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#172]
https://allthetropes.miraheze.org/wiki/Category:Trope_Workshop

SPF mentioned we had some orphaned revisions, this must be the place from where they are from.

If possible, we need all database records matching these pages in this namespace restored to their rightful place.

**Comment by Southparkfan** [comment]
See most recent server admin logs, fixed.

**Comment by Arcane21** [comment]
Still needs some manual DB cleanup, plz reopen till then.

**Comment by Arcane21** [comment]
Here's all the pages we need linked to that category:

https://allthetropes.miraheze.org/wiki/Special:WhatLinksHere/Template:Trope_workshop

**Comment by NDKilla** [comment]
Close per irc
