### ISSUE TITLE
Please import wikiconstitucio

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#174]
Hi, wikiconstitucio had a wiki in Orain, and it would be great to have the content at https://wikiconstitucio.miraheze.org/ -- thank you.

**Comment by revi** [comment]
Who should be the founder?

**Comment by quimgil** [comment]
Icaria36 is already the founder of that wiki -- see https://meta.miraheze.org/wiki/User_talk:Icaria36

**Comment by quimgil** [comment]
If you mean who was the founder of wikiconstitucio in Orain, it was either QuimGil or Victorgc (or a similar wiki username with "Victor", who is still around to become an admin of the new wiki).

**Comment by revi** [comment]
Import is done, check for the data. :-)
