### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#175]
```
Login error 
Meta uses cookies to log in users. You have cookies disabled. Please enable them and try again.
```
I have confirmed I have cookies enabled for meta.miraheze.org, still this error is coming.

@Reception123 is saying he cannot edit/save. I currently don't have time to investigate. Last successful edit accordng to -feed is this.
```
07:59:47 <+MirahezeRC> allthetropeswiki * [[The Country Bears/Funny]] !N https://allthetropes.miraheze.org/w/index.php?oldid=1323816&rcid=1975276 * 18.251.6.169 * (+556) *crunch* Aw no!
```

**Comment by Reception123** [comment]
Revi restarted HHVM and nginx, no effect.

**Comment by Reception123** [comment]
Similar issue reported here : https://www.mediawiki.org/wiki/Thread:Project:Support_desk/Wiki_uses_cookies_to_log_in_users._You_have_cookies_disabled._Please_enable_them_and_try_again._Please_help_:%28

**Comment by revi** [comment]
ori at freenode #mediawiki suggests that it's redis error but I don't have access to ```redis-cli``` (which is probably not on mw1)

**Comment by Southparkfan** [comment]
Yeah, known problem with Redis. Restarted Redis.

**Comment by JohnFLewis** [comment]
Taking to investigate. Likely linked with the extremely weird memory usage on misc1.

**Comment by JohnFLewis** [comment]
looking at this now.

**Comment by JohnFLewis** [comment]
No evidence of any issues. seem internally a software issue where our config is not too verbose about. tried to reproduce a week or two ago and couldn't. sporadic.
