### ISSUE TITLE
Add BGO extensions, NS config, and user rights

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#177]
Discussed on IRC. I haven't actually discussed this with BGO founders but I was an active sysop on the wiki and I'd like to continue it. 

Assigning @Southparkfan for the import itself (he has a backup). I'll handle extensions, config, and user rights myself later :)

http://bgo.miraheze.org

**Comment by NDKilla** [comment]
Import done by SPF

**Comment by revi** [comment]
I also have a dump received from SPF, but he said you have to process extensions first while I process #176. Quick checking at the dump, you need scribunto enabled. (SPF: You can assign this to me if you want me to handle this. (since I'm going to bed now I will do it by tomorrow.)

**Comment by revi** [comment]
Any progress?

**Comment by Reception123** [comment]
@NDKilla @revi Not sure if this is still going on..
