### ISSUE TITLE
HHVM failure

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#178]
Reading HHVM logs says segmentation fault, but cannot read ```/tmp/stacktrace.*****.log```.

**Comment by Southparkfan** [comment]
I need the "*****".

**Comment by revi** [comment]
I meant to say 'anything'.
Latest retry log: 28624.

**Comment by JohnFLewis** [comment]
root@mw1:/tmp# ls -l stacktrace.28624.log
-rw------- 1 www-data www-data 1770 Oct  5 06:31 stacktrace.28624.log

All is correct.
