### ISSUE TITLE
db crashed on search

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#179]
Re-creating #119.

**Comment by revi** [comment]
Ping.

**Comment by JohnFLewis** [comment]
I've converted 8stationwiki's table to InnoDB, which puts it in line with all other tables. this should prevent crashes on 8stationwiki.

Need to debate with myself if I should do it manually, bash script it or work on a MediaWiki maintenance script -- but before that I need to make changes to MW.

**Comment by JohnFLewis** [comment]
Done for all wikis (with the extremely helpful support of @jynus)!
