### ISSUE TITLE
OAuth Management impossible

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#180]
[Downstream phab.wm.o ticket](https://phabricator.wikimedia.org/T115305)

OAuth is installed, but there is no special page for requesting/granting it. My local test environment works fine with OAuth - I don't know what's different on production. Permission granted is exactly same.

**Comment by JohnFLewis** [comment]
I've been looking at this and I can't see an issue. Likely a re-occurrence of the old Translation extension issue so @Southparkfan should be able to investigate as he handled that.

**Comment by revi** [comment]
Blocked by [T132454](https://phabricator.wikimedia.org/T132454).

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T93.
