### ISSUE TITLE
Login blank page

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#183]
When I try to log in on meta  (https://meta.miraheze.org/w/index.php?title=Special:UserLogin&action=submitlogin&type=login&returnto=Special:RecentChanges), I get a blank page. As well as when I try to access RC I first get a load problem and only then it loads.
@Southparkfan @JohnFLewis @revi

**Comment by Reception123** [comment]
Possibly problems are from RecentChanges, since the DDoS attack.

**Comment by Southparkfan** [comment]
Fixed.
