### ISSUE TITLE
Support multi-server redundancy with MediaWiki

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#199]
Allow MediaWiki to run along multiple servers. Has upstream infra dependencies on static images and upstream CreateWiki on database lists.

**Comment by Southparkfan** [comment]
CreateWiki is done.

**Comment by Southparkfan** [comment]
@JohnFLewis static images is up to you.

**Comment by Southparkfan** [comment]
https://static.miraheze.org/ now has /mnt/mediawiki-static as docroot.
