### ISSUE TITLE
level12wiki gone

### ISSUE THREAD

**Issue by revi** [miraheze/mw-config#201]
``` 13:15, 4 October 2015 Reception123 (Talk | contribs | block) created the wiki "level12wiki" (Per ]]Special:RequestWikiQueue/121) ```

When I access https://level12.miraheze.org/wiki/,

```404 Wiki Not Found```

I think something with DB?

**Comment by Reception123** [comment]
Yes, szkwiki has the same issue
@revi

**Comment by Reception123** [comment]
@Southparkfan @JohnFLewis

**Comment by revi** [comment]
You do not need to ping us, we are automatically subscribed by default.

**Comment by JohnFLewis** [comment]
I don't believe it is database side, but I'll take this and investigate worst case since SPF won't be here for a few more hours.

**Comment by JohnFLewis** [comment]
Databases exist, but not to CreateWiki.

MariaDB [metawiki]> select * from cw_wikis where wiki_dbname = "level12wiki";
Empty set (0.00 sec)

**Comment by JohnFLewis** [comment]
Definitely CreateWiki.

root@mw1:/srv/mediawiki/dblist# grep -rl "level12wiki" *
all.dblist.bak
private.dblist.bak

**Comment by JohnFLewis** [comment]
This is the case for many many more wikis.


root@mw1:~# grep -Fxv -f all.dblist all.dblist.bak
jereswiki|Mračna Jeres|sr-el|
liutfprwiki|Licenciatura em Informática|pt-br|
teleportwiki|Téléport|fr|
worldnewswiki|世界新聞|zh-tw|
iqtwiki|IQT Microfab Wiki|en|
wikiconstituciowiki|WikiConstitució|ca|
aegyptiacawiki|Encyclopaedia Aegyptiaca|en|
sourcewiki|Source Code Wiki|en|
northumbriapqpgswiki|Postgraduate / Post-Qualifying S|en|
szkwiki|Szabadkőműves Wiki|hu|
portalwiki|Portalpedia|en|
level12wiki|Level 12|en|
czechmodwikiwiki|Česká wiki o MC módech|cs|
bgowiki|Board Game Online Wiki|en|
drspwiki|Drs. P Wiki|en|
tesztwiki|Teszt Wiki|hu|
oolwiki|ool|en|
cagencywikiwiki|Call Agency WIKI|fr|
worldpediawiki|世界大典|zh-tw|
wikiacawiki|WikiACA|frc|
philchariowiki|Philchario|pt-br|
librewiki|리브레 위키|ko|
sintwindpiwiki|SintWindPI|en|
rtcsnipwiki|RTC Snippets|en|
enwelcomewiki|Welcome Wiki|en|
frwelcomewiki|Welcome Wiki|fr|
dewelcomewiki|Welcome Wiki|de|
itwelcomewiki|Welcome Wiki|it|
grwelcomewiki|Welcome Wiki|grc|
rowelcomewiki|Welcome Wiki|ro|
arwelcomewiki|Welcome Wiki|ar|
tuwelcomewiki|Welcome Wiki|tr|
shotgunultimatewiki|Shotgun Ultimate|en|
cittanostraunserestadtwiki|Città Nostra Bolzano – Unsere|de|
applebranchwiki|AppleBranch|en|
makedoniumwiki|Македониум|en|

**Comment by JohnFLewis** [comment]
Reverted things back pre. DB managed and all is back as is.
