### ISSUE TITLE
[Question] Where is $wgStylePath?

### ISSUE THREAD

**Issue by ChiyoOsaka** [miraheze/mw-config#212]
Just comparing things and I noticed that `$wgStylePath` isn't in your [LocalSettings.php](https://github.com/miraheze/mw-config/blob/master/LocalSettings.php), so I was wondering...where is it?

**Comment by Southparkfan** [comment]
It is the MediaWiki default: https://www.mediawiki.org/wiki/Manual:$wgStylePath
