### ISSUE TITLE
Upgrade 1.26

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#213]
As 1.26 came out a few days ago, I think we should soon upgrade.

**Comment by Southparkfan** [comment]
Yeah, I know. It's currently blocked by the process of adding mw2.miraheze.org.

**Comment by Southparkfan** [comment]
mw2 is added.

Steps:
- [ ] Ensure CreateWiki SQL files have the new files
- [ ] Ensure everything works fine as it should
- [ ] Notify people about the upgrade
- [ ] Make wikis read-only
- [ ] Make backups of everything
- [ ] Redirect all traffic to mw2, upgrade mw1
- [ ] Purge Varnish cache
- [ ] Redirect all traffic back to mw1, mw2's future TBD.
- [ ] Purge Varnish cache again

**Comment by Southparkfan** [comment]
Note about CreateWiki SQL files: the following SQL files have been added in 1.26 exts:
> ./extensions/CentralAuth/db_patches/patch-gu_cas_token.sql
76a78
> ./extensions/Flow/db_patches/patch-flow_workflow_update_timestamp_idx.sql
79a82,88
> ./extensions/Flow/db_patches/patch-reference_wiki-phase1.5_WMF.sql
> ./extensions/Flow/db_patches/patch-reference_wiki-phase1.sql
> ./extensions/Flow/db_patches/patch-reference_wiki-phase2.sql
> ./extensions/Flow/db_patches/patch-reference_wiki-phase3.sql
> ./extensions/Flow/db_patches/patch-reference_wiki-phase4.sql
> ./extensions/Flow/db_patches/patch-reference_wiki-phase5.sql
> ./extensions/Flow/db_patches/patch-reference_wiki.sql
135a145
> ./extensions/OAuth/backend/schema/mysql/developer_agreement.sql
137a148
> ./extensions/OAuth/backend/schema/sqlite/developer_agreement.sql

**Comment by Southparkfan** [comment]
CentralAuth's patch needs to be applied manually. Flow's patches do not seem needed, and OAuth's patch has been added to CreateWikiSQLfiles in 55f5dda7f903707e0735a72343d9ba1e0df0457a.

**Comment by NDKilla** [comment]
Closing as 1.26 is installed on all wikis? :P reopen if needed
