### ISSUE TITLE
Wikitext discussion pages in spiralwiki need to be converted or migrated to Flow

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#23]
See for instance https://spiral.wiki/wiki/Talk:Happiness_for_everyone
I don't know what is possible or the current state of the art, but I have seen wikitext discussion pages converted to Flow boards in mediawiki.org, and this would be the solution preferred.
If this is not possible or too complex, then the option of archiving wikitext pages and starting new Flow boards would work as well.

**Comment by Southparkfan** [comment]
Oh sorry! I only migrated user_talk pages! Will do the others now.

**Comment by JohnFLewis** [comment]
All done.
