### ISSUE TITLE
RC doesn't show all changes

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#234]
Example https://tyrolmountains.miraheze.org/w/index.php?title=Special:RecentChanges&limit=500&hidebots=0&days=9223372036854775807
I put maximum days but the creation and editing of page "Zugspitze" doesn't show up.

**Comment by Reception123** [comment]
This could have an issue with " A rule of thumb is that everything that can be seen on Special:RecentChanges is counted as activity."

**Comment by Southparkfan** [comment]
That is because that page was created before https://www.mediawiki.org/wiki/Manual:$wgRCMaxAge (90 days ago). The recentchanges table does not contain entries older than 90 days.

**Comment by Reception123** [comment]
Oh, okay. In that case this "issue" is solved only we need to find a solution as like that we can't identify wikis that have no edits since they were created.

**Comment by NDKilla** [comment]
Closed with 5732a52
