### ISSUE TITLE
Internal error 

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#235]
This doesn't happen all the times but frequently. Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database: Can't connect to MySQL server on '185.52.1.77' (111) (185.52.1.77))

@Southparkfan

**Comment by Southparkfan** [comment]
I cannot reproduce this @Reception123.

**Comment by Reception123** [comment]
I understand, it only happens sometimes.

**Comment by NDKilla** [comment]
This always happens any time the MySQL server OOM's, closing as a known and possibly fixed issue outside of our control (besides server upgrades, which I don't believe this specific issue should cover, and DB optimization, which is kind of continuously mentioned)
