### ISSUE TITLE
MediaWiki:Copyright doesn't appear in the footer

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#24]
https://meta.miraheze.org/wiki/Main_Page doesn't state any license -- and this seems to be the same for any page in any Miraheze wiki.

https://meta.miraheze.org/wiki/MediaWiki:Copyright is correct, so I guess that there is a configuration somewhere defining that it shouldn't be shown. It should.

**Comment by Reception123** [comment]
#33 I think could fix it

**Comment by quimgil** [comment]
The footer has now proper licensing. Resolving.
