### ISSUE TITLE
Database error during update.php

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#278]
Pretty sure existing tables don't usually cause the update.php script to error and quit mid-script

script: /srv/mediawiki/w/maintenance/update.php --wiki adnovumwiki
Relevant error and stack trace:
Creating globalblocks table ...A database query error has occurred.
Query: CREATE TABLE `global_block_whitelist` (
 gbw_id int(11) NOT NULL PRIMARY KEY, -- Key to gb_id in globalblocks database.
 gbw_address varbinary(255) NOT NULL,
 gbw_by int(11) NOT NULL, -- Key to user_id
 gbw_by_text varchar(255) NOT NULL,
 gbw_reason varchar(255) NOT NULL,
 gbw_expiry binary(14) NOT NULL
 ) ENGINE=InnoDB

Function: DatabaseBase::sourceFile( /srv/mediawiki/w/extensions/GlobalBlocking/includes/../globalblocking.sql )
Error: 1050 Table 'global_block_whitelist' already exists

Backtrace:
#0 /srv/mediawiki/w/includes/db/Database.php(1076): DatabaseBase->reportQueryError('Table 'global_b...', 1050, 'CREATE TABLE `g...', 'DatabaseBase::s...', false)
#1 /srv/mediawiki/w/includes/db/Database.php(3979): DatabaseBase->query('CREATE TABLE `g...', 'DatabaseBase::s...')
#2 /srv/mediawiki/w/includes/db/Database.php(3893): DatabaseBase->sourceStream(Resource id #419, false, false, 'DatabaseBase::s...', false)
#3 /srv/mediawiki/w/includes/installer/DatabaseUpdater.php(668): DatabaseBase->sourceFile('/srv/mediawiki/...')
#4 /srv/mediawiki/w/includes/installer/DatabaseUpdater.php(691): DatabaseUpdater->applyPatch('/srv/mediawiki/...', true, 'Creating global...')
#5 [internal function]: DatabaseUpdater->addTable('globalblocks', '/srv/mediawiki/...', true)
#6 /srv/mediawiki/w/includes/installer/DatabaseUpdater.php(455): call_user_func_array(Array, Array)
#7 /srv/mediawiki/w/includes/installer/DatabaseUpdater.php(420): DatabaseUpdater->runUpdates(Array, true)
#8 /srv/mediawiki/w/maintenance/update.php(169): DatabaseUpdater->doUpdates(Array)
#9 /srv/mediawiki/w/maintenance/doMaintenance.php(103): UpdateMediaWiki->execute()
#10 /srv/mediawiki/w/maintenance/update.php(214): require_once('/srv/mediawiki/...')
#11 {main}

**Comment by Southparkfan** [comment]
Known error.

Workaround is to run the same command afterwards again.
