### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#286]
I currently dont have access to IRC but I see Miraheze is giving 502 again... @Southparkfan

**Comment by revi** [comment]
Restarted HHVM.

**Comment by revi** [comment]
No stacktrace on `/tmp`.

**Comment by Southparkfan** [comment]
Needs an incident report.

**Comment by NDKilla** [comment]
Repeatedly caused by HHVM crashing. No idea why fallback isn't working. Check meta server admin log. HHVM seg-faulted less than 3 minutes after I started it earlier

**Comment by Reception123** [comment]
Sorry for the reference, it was my mistake.
