### ISSUE TITLE
Install Extension:WebChat

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#287]
Stable extension. Not in use on WMF wikis, but shouldn't be a security concern hopefully.
Just be careful with configuration as it will probably be confusing and new arrays will have to be added.
https://www.mediawiki.org/wiki/Extension:WebChat

**Comment by Reception123** [comment]
It is a WMF (mediawiki repo) extension. Will make a PR for installing.

**Comment by Southparkfan** [comment]
Security review: OK to use.

**Comment by JohnFLewis** [comment]
I can't see any wiki requests asking for this?

**Comment by Southparkfan** [comment]
All The Tropes?

**Comment by JohnFLewis** [comment]
Nope, no extension request lists from Arcane have it listed.

**Comment by NDKilla** [comment]
I think ATT wanted it before, but may have abandoned it. Anyways, I'm planning on using it on quantix and games wikis :p

**Comment by JohnFLewis** [comment]
You can handle it then if its essentially for you.

**Comment by JohnFLewis** [comment]
This was/is a security review ticket. that's been done, if NDK wants to install it for himself he can.
