### ISSUE TITLE
publictestwiki.com captcha fails

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#288]
@Southparkfan 
https://publictestwiki.com/w/index.php?title=Special:UserLogin&returnto=Main+Page&type=signup
Captcha says ERROR: Invalid domain for site key
I'm assuming this is because of how the captcha key's are configured and/or registered.
Let us (at publictestwiki.com) know if we can do anything to fix this, or if it's a config issue.
For now, making a notice to signup at login.miraheze.org or meta.miraheze.org

**Comment by Southparkfan** [comment]
Fixed a few days ago.
