### ISSUE TITLE
Things to be done so Miraheze works completely

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#32]
Things to be done so that Miraheze works completely (more or less)
- [ ] In-wiki
 - [ ] Create and design Mainpage
 - [ ] Create policies
 -  [ ] Import templates and etc.
- [ ] CreateWiki developement
 - [ ] Configure closing wikis
 - [ ] Possibly! Configure editing wikis (name, etc.)
- [ ] Advertising 
- [ ] IRC
 - [ ] Create IRC feed bot @Southparkfan #26 
 - [ ] Make MirahezeGitHub post issues on IRC

**Comment by Reception123** [comment]
@Southparkfan @JohnFLewis

**Comment by JohnFLewis** [comment]
I liked to keep this easily tracked so; wiki content is off topic here. Create wiki issues should go on the CreateWiki extension tracker. IRC see,s already tracked.

Please follow the ticket-per issue approach unless things seems so minuscule.
