### ISSUE TITLE
Separate public and private media (/srv/mediawiki-static/)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#322]
A safe and secure method that optimises public content transfer yet keeps private wiki data secure is not a one-bird situation.

As I started with Orain, the move for private wiki's content to an off-the-web directory is an ideal situation with Auth handled at the MediaWiki level.

**Comment by Southparkfan** [comment]
https://phabricator.wikimedia.org/diffusion/MW/browse/REL1_26/img_auth.php;c2d388d7f11c2658c3a0ca215883cc83673a22a7$138? img_auth.php will be cached for public wikis, and won't be cached for private wikis.
The only disadvantage is that we either will decomission static.miraheze.org, or ALL static content servers now need to have MediaWiki installed?

Oh, and we would require a rewrite rule to rewrite https://static.miraheze.org/metawiki/3/35/Miraheze_Logo.svg to https://static.miraheze.org/w/img_auth.php?path=/mnt/mediawiki/metawiki/3/35/Miraheze_Logo.svg or whatever.

Example (not tested actually yet!): rewrite ^/[a-z0-9]/([a-z])/([a-z0-9])/(.*) /w/img_auth.php/$2/$3/$4?dbname=$1

This would need an img_auth.php patch too.

**Comment by JohnFLewis** [comment]
Not being separated.
