### ISSUE TITLE
Override messages containing "Wikimedia Foundation" with "Miraheze" messages

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#34]
When I log out this is what I see :  Logging you out from other wikis of the Wikimedia Foundation

**Comment by Southparkfan** [comment]
https://github.com/wikimedia/mediawiki-extensions-WikimediaMessages for us would be the perfect solution I guess.

**Comment by Southparkfan** [comment]
https://github.com/wikimedia/mediawiki-extensions-WikimediaMessages/commit/37585a58c68c9f343a094d148438384962b404fd

**Comment by JohnFLewis** [comment]
Done.
