### ISSUE TITLE
Install FlaggedRevs

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#350]
Per RF.

**Comment by Reception123** [comment]
@Southparkfan

**Comment by Reception123** [comment]
PR at mediawiki repo. Waiting to be merged.

**Comment by Reception123** [comment]
@Southparkfan

**Comment by Reception123** [comment]
Config preferences is needed for it to be installed for the specific wiki. Still waiting.

**Comment by JohnFLewis** [comment]
No resp in a month in terms of config. This is therefore a dead ticket. If they provide config details, please comment on this.
