### ISSUE TITLE
Delete allthetropestestwiki, spiraltestwiki and poserdazfreebiestestwiki

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#356]
Delete these wikis as they are no longer needed

**Comment by JohnFLewis** [comment]
poserdazfreebiestestwiki was in deleted.dblist so I deleted it with 2 other wikis.

**Comment by Southparkfan** [comment]
Kill them.

**Comment by JohnFLewis** [comment]
Death shall be fierce.

**Comment by JohnFLewis** [comment]
Deleted. Will remove confs in a few.
