### ISSUE TITLE
fatal error on ggdr.mh.o

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#359]
```
Fatal error: Maximum execution time of 30 seconds exceeded in /srv/mediawiki/w/includes/parser/Preprocessor_DOM.php on line 1113
```
Regularly getting this error trying to load the main page of the wiki, along with random 504 gateway timeouts. Unknown if it's affecting other wikis

**Comment by Southparkfan** [comment]
Fixed I guess?
