### ISSUE TITLE
Backup thoughtonomywiki (DO NOT MAKE THE DUMP PUBLIC!)

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#372]
Backup thoughtonomywiki, search for the email address of the founder in the db and send the backup via mail.

**Comment by JohnFLewis** [comment]
1 month? really lacking. I'll do it.

**Comment by JohnFLewis** [comment]
Urm, the founder has no email.

**Comment by JohnFLewis** [comment]
Contacted the user via wiki to send me an email (standard john{{@}}miraheze.org, not the sysadmin/operations/steward one) so I'll send them the backup when they get to me.

In terms of physical work, this is done.
