### ISSUE TITLE
Still need these extensions installed on All The Tropes

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#373]
- [x] BetaFeatures
- [ ] NativeSvgHandler
- [ ] https://www.mediawiki.org/wiki/Extension:PageNotice
- [ ] https://www.mediawiki.org/wiki/Extension:SandboxLink (This because it resolves a few issues with the gadget, see extension page for more details)
- [x] WikiLove
- [ ] Vote
- [x] Youtube

**Comment by NDKilla** [comment]
Youtube's apparently been done (enabled according to the file).
Sorry about the delay on some of these, and thanks for the new issue.

**Comment by Reception123** [comment]
@Arcane21 WikiLove is done

**Comment by Reception123** [comment]
@Arcane21 BetaFeatures done

**Comment by JohnFLewis** [comment]
Vote is unmaintained so {{notdone}}. An alternative may be available (or a maintainer!).

**Comment by Arcane21** [comment]
Well, we NEED it, or our reviews system is broken.

**Comment by JohnFLewis** [comment]
All done that can be done. Two extensions need security review.

**Comment by Reception123** [comment]
I will try finding a alternative.

**Comment by Reception123** [comment]
@Arcane21 SandboxLink is done by John.
