### ISSUE TITLE
Meta: not working on other wikis

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#38]
Linking Meta: does not work from other wikis

**Comment by Reception123** [comment]
@Southparkfan @JohnFLewis

**Comment by JohnFLewis** [comment]
It shouldn't. This is also a wiki issue as a request so please use that venue.

**Comment by Southparkfan** [comment]
I guess interwiki prefixes is a valid reason (except that there should be an issue about interwiki in general, and not just for this wiki) for a GH issue?
