### ISSUE TITLE
PageNotice (Security Review)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#381]
https://www.mediawiki.org/wiki/Extension:PageNotice for ATT.

**Comment by Southparkfan** [comment]
Result of review (yes, WMF-style):
- ./modules/ext.pageNotice.css: OK
- ./PageNotice.php: OK
- ./PageNotice.hooks.php: OK
- i18n files: OK
This extension can be used on Miraheze.

Additional note: I am not sure if the parsercache is used for those notices. Please test for any performance regressions.
