### ISSUE TITLE
All The Tropes needs all extensions that can be made opt-in BetaFeatures added

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#383]
BetaFeatures is installed, but we need all features that can be designated opt-in enabled as such for ATT.

**Comment by JohnFLewis** [comment]
Could you please be more specific?

**Comment by Arcane21** [comment]
Popups, VectorBeta, VisualEditor, MulmediaViever et al all need to be made opt-in features.

By request of some users who want to have a choice, myself included.

**Comment by JohnFLewis** [comment]
Done.
