### ISSUE TITLE
Parsoid can't contact private wikis

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#394]
Parsoid is unable to contact private wikis as the read right is not available.

Example is biblicalwiki. Parsoid was occasional using IPv6 to speak with mw* but I have since disabled IPv6 on parsoid1.

The disabling of forwarding cookies caused the issue and the replacements does not work. This should be fixed or reverted back to forwarding cookies (bad security though).

**Comment by Southparkfan** [comment]
Fixed. 5737cba8e5df540045de9c7ce701c4ccfdc113c8

**Comment by JohnFLewis** [comment]
Hm bad NGINX doing that.

**Comment by Southparkfan** [comment]
Apache is open-source, so ;)
