### ISSUE TITLE
Install/Review ContactPage

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#396]
Per RF

**Comment by JohnFLewis** [comment]
ContactPage is good, will install.

**Comment by JohnFLewis** [comment]
Technically installed now.

**Comment by JohnFLewis** [comment]
Needs configuration details from user.

**Comment by JohnFLewis** [comment]
@Reception123 closing this now as the original issue was resolved.

**Comment by JohnFLewis** [comment]
A config idea exists by the user. Will handle.
