### ISSUE TITLE
Extension issues on ATT

### ISSUE THREAD

**Issue by Arcane21** [miraheze/mw-config#399]
We need Visual Editor completely removed, it's been causing a lot of issues, and we need MultiUpload installed.

We also need InputBox reinstalled. (removed awhile back due to editing issues, should be fixed now)

**Comment by NDKilla** [comment]
MultiUpload was disabled globally a while back. Is MsUpload an acceptable replacement

**Comment by Arcane21** [comment]
That'll work.

**Comment by JohnFLewis** [comment]
What sort of issues is VisualEditor causing? It seems fine to me on the wiki.

**Comment by Arcane21** [comment]
We've gotten complaints it's not very fast or efficient, has caused some alignment issues with the skin tabs, and most of our editors prefer the stock editor anyway,

Also, Media Viewer can be removed for similar reasons.

**Comment by NDKilla** [comment]
@arcane21 Maybe mark visual editor as beta or something or set default user options to disable it?

**Comment by Arcane21** [comment]
That'll be fine

**Comment by Reception123** [comment]
@Arcane21 VE is beta now and MSUpload is enabled.
