### ISSUE TITLE
Coordinating efforts to combat spam

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#41]
Spam is still a problem. I can try to fine tune rules in my own wiki, but the fact is that all Miraheze wikis are receiving the same kind of spam, so we should better document and coordinate efforts. Where to start?

PS: meanwhile, I will cleaning the spam of spiralwiki, no need for you to delete content/users there.

**Comment by quimgil** [comment]
How are we preventing edits including external links? All the spam pages I'm seeing include external links. We could start fine tuning antispam here.

**Comment by quimgil** [comment]
The other point is user account creation. Even if we delete the user pages, the user accounts remain: https://spiral.wiki/wiki/Special:ListUsers. How can we prevent better the creation of spam accounts?

**Comment by quimgil** [comment]
Progress! The filter set by @NDKilla filtered effectively all attempts of spam made tonight. Dozens of new accounts were created though, and I fear that they can still be used to spam the wiki in a few days.
Should we install https://www.mediawiki.org/wiki/Extension:UserMerge, which seems to be the tool used to remove users quickly?

**Comment by JohnFLewis** [comment]
I'm against removing users unless it is technically required really. Missing IDs and the fact accounts are automatically global.

**Comment by quimgil** [comment]
Check how the "UserMerge" extension works. Unsurprisingly, it doesn't actually remove users, but it merges all the spam accounts in a single one, with almost the same end result (invalidating spam accounts).

**Comment by quimgil** [comment]
... and back to not progress. I just deleted dozens of spam pages, including types of User pages that were filtered before, I believe because now the accounts are old enough to bypass the filter.
Let me share the dimensions of the problem of spam user accounts in https://spiral.wiki/wiki/Special:ListUsers. We have more than 300 created since Saturday. Almost 100 fake accounts created on a daily basis. I think it is reasonable to say that I don't want that dormant problem in my wiki, soon thousands of usernames that were created for nothing good and can be reused at any time by their creators.

**Comment by NDKilla** [comment]
I wonder if bots are attracted to your custom domain. It's weird spam bots keep going to your wiki and not others even after changing hosts. 

Back to the matter at hand, account creation SHOULD be limited to 5 accounts per day by the same IP. Maybe I was wrong about them being on the same botnet. 

@quimgil have you tried blocking one of the spam accounts with account creation disabled and autobloxk enabled?

**Comment by quimgil** [comment]
espiral.org / spiral.wiki is an "old" project and the rest of Miraheze ones are new. I think that is the simple explanation.
> have you tried blocking one of the spam accounts with account creation disabled and autobloxk enabled?
Sorry, it must be late but I don't understand.  :(

**Comment by JohnFLewis** [comment]
I'll sit down and improve the filters when I get back tomorrow to try and reduce what gets through edit wise.

**Comment by quimgil** [comment]
Ref UserMerge extension, I have created #50.

**Comment by quimgil** [comment]
I have added a regexp to MediaWiki:Titleblacklist in spiralwiki that should prevent the creation of some accounts.

**Comment by quimgil** [comment]
The QuestyCaptcha we have is clearly being solved by bots. The fact that our LocalSettings.php is public probably doesn't help. How can I add own questions/answers for spiralwiki? Could you add an example, so I can contribute more Q&A directly, please?

Q: "Happiness for... ?"
A: "everyone" (I hope it is case insensitive)

**Comment by addshore** [comment]
The reason bots will be hitting spiralwiki more than other miraheze wikis is due to the fact that there has been a mediawiki wiki at the spiralwiki domain for longer than any of the miraheze domains / subdomains.

Bots only spam wiki installs they know about and spiralwiki is old!

The only way to effectively combat the spam will be to
 1 - Enable a good captcha (such as recaptcha)
 2 - Have a couple of good abuse filter rules

**Comment by JohnFLewis** [comment]
Spam bot editing seems resolved by AbuseFilters. #57 tracks switching the captcha to something more secure. Closing.
