### ISSUE TITLE
RC doesn't display all edits

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#410]
This is an example: https://publictestwiki.com/w/index.php?title=TestWiki:Request_permissions&diff=1208&oldid=1207 
SleepyMode (the user that edited) does not have bot permissions, therefore it should show up.

**Comment by JohnFLewis** [comment]
Does not exist in the RC table. Same for several edits on metawiki. Looking,

**Comment by JohnFLewis** [comment]
Can't find an immediate cause to this. No evidence of a failed query with MariaDB, could be killed due to slowness but also can't find evidence of this.

**Comment by JohnFLewis** [comment]
Not noticed this lately. Probably fixed as a result of some MariaDB tests.
