### ISSUE TITLE
Kill LQT for Flow

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#416]
LQT should just die, it's bad honestly. Flow is already in active use on several wikis and has the infra to support it well.

#316 is an issue relating to this (which I'm going to close).

Assigned to SPF as the database is messed up but really should be fixed in some form as LQT is just bad and the longer we keep it, the less motivated we are to kill it. Flow or wikitext honestly.

**Comment by JohnFLewis** [comment]
Customary pings for @labster and @Arcane21. It'll take time but either way, it will happen (when is a question).

**Comment by Arcane21** [comment]
Move us to Flow whenever you find practicable. LQT does have some issues I'd love to leave in the dust. It also seems to make making backups of our content a pain (according to SPF), so once we've successfully upgraded, hose the LQT tables and see if we can get a straight XML dump as opposed to an SQL dump plz (current revision only, need so I can do some tests/make sure we get a proper dump).

**Comment by labster** [comment]
What no I love LQT :potable_water: it is best premium technology.

I'd like to have a backup of the LQT data before upgrading.  Or, y'know, a full backup of ATTwiki.

**Comment by NDKilla** [comment]
@labster no backups for you

**Comment by Arcane21** [comment]
In all seriousness, making sure we can do a full ,backup would be nice if possible, and a separate dump of the LQT tables as a just in case would be good if possible to do.

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T211.
