### ISSUE TITLE
Missing images / thumbnails in spiralwiki

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#42]
All of  a sudden the logo and some images are missing. Or not the images but the thumbnails?

See 

* https://spiral.wiki/wiki/Happiness_for_everyone 
* https://spiral.wiki/wiki/0
* https://spiral.wiki/wiki/File:Logo_Otra_Democracia_Es_Posible.jpg

**Comment by quimgil** [comment]
The images are back. Not the logo, though.

**Comment by quimgil** [comment]
Any idea of why the logo disappeared and how to bring it back? I plan to send an announcement to the old subscribers on 2015-08-14 (in two days), and the lack of logo is the only showstopper.

**Comment by Reception123** [comment]
I can only say that the current logo is set to
		'spiralwiki' => "//$wmgUploadHostname/spiralwiki/f/fa/Espiralogo.svg",
not Logo_Otra_Democracia_Es_Posible.jpg

**Comment by JohnFLewis** [comment]
The logo does not exist, which is why it is not showing :)

I'll switch it now.

**Comment by Southparkfan** [comment]
Please give me a list of missing images/thumbnails. Logo needs to be re-uploaded, and the URL needs to be changed in the wgLogo array.

**Comment by quimgil** [comment]
Any idea why these images disappeared, and some of them reappeared? As far as I can see, then only one missing is the logo.

**Comment by Southparkfan** [comment]
I don't know why. If that wasn't a one-time issue, then please notify us.

**Comment by JohnFLewis** [comment]
Changed logo to the one on commons.

**Comment by quimgil** [comment]
Thank you for the good intentions, but... https://spiral.wiki/ got a logo, but it's the wrong one, displayed wrongly.   :(

Please use https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Spiral_project_logo.svg/135px-Spiral_project_logo.svg.png instead. Thank you.

**Comment by JohnFLewis** [comment]
Fixed!
