### ISSUE TITLE
Conversion of dblists to JSON

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#421]
For https://github.com/miraheze/CreateWiki/issues/27.

- [x] Convert all.dblist to JSON
- [x] Convert https://github.com/miraheze/mw-config/blob/946dbfb42ecf73f626488ad1cd2ff3af0a08d1a1/LocalSettings.php#L1917 as needed

**Comment by Southparkfan** [comment]
This is done now.

@JohnFLewis @NDKilla I kindly ask you to monitor performance. It seems to be a bit degraded, so..

**Comment by JohnFLewis** [comment]
Does this change still write a private.dblist?

**Comment by Southparkfan** [comment]
No.

Everything is in all.dblist now.

**Comment by JohnFLewis** [comment]
This breaks SiteMatrix then as it had a private lost input from private.dblist

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T213.
