### ISSUE TITLE
504 gateway timeout trying to change email

### ISSUE THREAD

**Issue by NDKilla** [miraheze/mw-config#429]
5:15:28 PM <FluffyVulpix> I can't change my email.
5:15:37 PM <FluffyVulpix> I made my account without an email
5:15:47 PM <FluffyVulpix> and i wanted to set an email.
5:16:03 PM <FluffyVulpix> When I try, I get a 504 gateway timeout error

Note that for me when I hit "Change email" after hitting change email the first time, typing new email and password,

Edit: It didn't do anything _for a while_. I'm impatient apparently. Confirming 504 timeout.

**Comment by JohnFLewis** [comment]
#430 mostly.
