### ISSUE TITLE
Internal Error when attempting to access CA

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#441]
Me and another user are getting this error. 
Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database: Unknown database 'pxgprojectwiki' (185.52.1.77))

You can try searching via Google in the meantime.
Note that their indexes of our content may be out of date.

  Search
Meta  WWW

**Comment by Reception123** [comment]
@JohnFLewis " wiki_dbname = pxgprojectwiki - can someone delete it when they read this message please?" you said something about it in chat. I think someone did something wrong there..

**Comment by JohnFLewis** [comment]
i asked as part of an on-wiki report of the issue.

It appears I typoed when dropping it from the cw_wikis table which is the issue here. No one did anything to cause it except my deletions a few days ago.

**Comment by JohnFLewis** [comment]
Resolved. Not what I thought, some entries remained in centralauth for some reason - 2 entries exist. Which is weird as I expect 3 at minimum (Reception, the founder and myself). Seems like the script failed to remove centralauth entries for this one wiki?
