### ISSUE TITLE
Install/Review FlaggedRevs

### ISSUE THREAD

**Issue by Reception123** [miraheze/mw-config#450]
New request. Config: "Hello, I was wondering if it would be possible to allow anonymous users to edit my wiki but with the changes being subject to review by an administrator before they are saved. Can this be done?"

**Comment by JohnFLewis** [comment]
Closing per #350. Without configuration data, it can't be enabled. Furthermore it doesnt need a review and installation is very strongly dependent of configuration.

I'd say employ the 'make a pull request to get this done' tactic.
