### ISSUE TITLE
RecentPages (Sec)

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#451]
https://www.mediawiki.org/wiki/Extension:RecentPages for christipedia.

**Comment by labster** [comment]
This one fails security review.  It has a pretty obvious XSS hole.

**Comment by labster** [comment]
I asked the user to swap this extension out for Extension:NewestPages, which easily passed security review, and he agreed quickly.  Closing this issue, as the XSS errors in RecentPages are no longer our problem.
