### ISSUE TITLE
Database error on userpage

### ISSUE THREAD

**Issue by labster** [miraheze/mw-config#457]
https://drunkenpeasantswiki.miraheze.org/wiki/User:Username1234567890 shows:

A database query error has occurred. This may indicate a bug in the software.
    Function: UserProfile::getProfile
    Error: 1146 Table 'drunkenpeasantswikiwiki.user_profile' doesn't exist (185.52.1.77)

**Comment by JohnFLewis** [comment]
Caused by https://github.com/miraheze/mw-config/commit/6dcad7a7267a0f8dcd1687f73f1805ef34735c67 Merged 1 1/2 months ago.

**Comment by JohnFLewis** [comment]
Remove https://github.com/miraheze/mw-config/blob/master/LocalSettings.php#L615 to fix it please!
