### ISSUE TITLE
Why is this user blocked?

### ISSUE THREAD

**Issue by labster** [miraheze/mw-config#460]
https://meta.miraheze.org/w/index.php?title=Special%3ACentralAuth&target=Ant  OMG we banz0red him hard.

Except he's not on here: https://allthetropes.org/wiki/Special:Log/block?page=User:Ant
And not on here: https://allthetropes.org/wiki/Special:BlockList

Is this some consequence of the import?  If so, it's OK to remove any Oranian Era blocks.  We'll reblock people, I'm sure.

**Comment by labster** [comment]
@Arcane21 ^, and also make a Phabricator account here please for the future:  https://phabricator.miraheze.org/

**Comment by Arcane21** [comment]
Registered. And yeah, unless we had a very good reason for a Orain era block, undo it here.

**Comment by JohnFLewis** [comment]
@Southparkfan just an idea here but could it be the issue I the user Ant on Allthetropeswiki has the same user ID as s user who was previous indefinitely blocked?

If so, I'm calling this s non-issue in things we can control and leaving it to @labster and @Arcane21 to deal with locally however they wish to.

Thoughts?

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T229.
