### ISSUE TITLE
Flow installed half way

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#48]
Flow was installed and working for a few days in spiralwiki, but now...

* according to https://spiral.wiki/wiki/Special:Version the extension is installed
* the existing wikitext discussions have been archived correctly
* however, Flow boards are missing, and whoever starts a new discussion will start a wikitext discussion.

See for instance https://spiral.wiki/w/index.php?title=Talk:Happiness_for_everyone&action=edit&redlink=1

**Comment by JohnFLewis** [comment]
Flow was disabled by @Southparkfan it seems.

**Comment by quimgil** [comment]
I would love to have it back, if possible.
PS: New Moon! I'm planning to send our newsletter tonight.

**Comment by quimgil** [comment]
Hm. https://spiral.wiki/wiki/Talk:Happiness_for_everyone has Flow but i.e. https://spiral.wiki/wiki/0 doesn't. I'm happy having Flow everywhere, no wikitext Talk / User_talk pages.

**Comment by JohnFLewis** [comment]
@quimgil yeah - I enabled it there to see why it was likely disabled. Since I see no real reason, enabled by default. Lack of shell means it should apply in 30 minutes.

**Comment by JohnFLewis** [comment]
And solved.
