### ISSUE TITLE
UserMerge extension

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#50]
Please provide the UserMerge extension https://www.mediawiki.org/wiki/Extension:UserMerge

Reasoning: spiralwiki has collected more than 1000 account just in one week, see https://spiral.wiki/w/index.php?title=Special:Log/newusers&offset=&limit=500&type=newusers&user= . Several spam filters effective right now are based on the age of the accounts. This is being very useful right now, but if we don't deal with these hundreds and soon thousands of spam accounts, the problem will come back to us.

UserMerge is deployed in Wikimedia servers. I don't know whether it should be available in spiralwiki or somewhere centrally, in order to merge spam accounts for all Miraheze wikis.

**Comment by JohnFLewis** [comment]
Looking at it; I'm still unsure how this would affect global accounts. My understanding is the extension deployment at the WMF is needed for some old CA code and resolving diverged accounts and merging local accounts into a global account on local wikis only.

**Comment by quimgil** [comment]
I think you are confusing UserMerge with MergeAccount, which, according to Special:Version, is already installed.

**Comment by JohnFLewis** [comment]
https://www.mediawiki.org/wiki/Extension:UserMerge is what I'm basing my comments on. It seems merging local accounts only, with no reference to how it behaves with CentralAuth or the idea of global accounts, I'm unsure on the fall out this will have honestly.

**Comment by quimgil** [comment]
I have asked at https://www.mediawiki.org/wiki/Topic:Sn2pmj5dayfvgtfi

**Comment by JohnFLewis** [comment]
Subscribed to topic. Will watch for activity.

**Comment by JohnFLewis** [comment]
Going to say no to MergeUsers (for now anyway).

I looked into the accounts and compiled a list of all accounts which weren't associated with a global account (so spiralwiki only) and then deleted them. A few still exists which aren't associated with a global account so I'm looking into that now.

**Comment by JohnFLewis** [comment]
The amount of accounts is significantly lower now actually. Less than 50 actually. I'll close this since the purpose of this issue has been resolved in theory. Reopen if you want.

**Comment by quimgil** [comment]
OK. Just for the record, the amount of new spam accounts add decreased because of MediaWiki:Titleblacklist‎‎
