### ISSUE TITLE
Use reCAPTCHA for wikis not QuestyCaptcha.

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/mw-config#57]

**Comment by JohnFLewis** [comment]
Resolved. Now deployed and detects I'm not a spambot so I didn't need to do a captcha. Only usage on spiral.wiki will see.

The issue is reCaptcha is managed by site. Currently miraheze.org and spiral.wiki are registered with the service to me. Custom domains possibly won't work at the minute but shouldn't be an issue.

@quimgil Enjoy and report back with results please!

**Comment by quimgil** [comment]
No new accounts created since we have recaptcha! I'm going to revert the restrictions I added to MediaWiki:Titleblacklist‎ a couple of days before.

Thank you.
