### ISSUE TITLE
Run the Flow script in spiralwiki to recover links to archived talk pages

### ISSUE THREAD

**Issue by quimgil** [miraheze/mw-config#58]
The talk pages of e.g.https://spiral.wiki/wiki/Happiness_for_everyone or  https://spiral.wiki/wiki/The_Spiral_project should include a link to the old discussion in wikitext. We had this the first time Flow was enabled, but it is missing since the second time.

**Comment by JohnFLewis** [comment]
Done (sort of). Flow doesn't allow the edit.php script append any wikitext at all so I've done this manually instead of my original plan of a bash script. All pages should now have {{Wikitext talk page converted to Flow}} on them.
