### ISSUE TITLE
Make VisualEditor working

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#68]
@JohnFLewis is going to work on that.

**Comment by JohnFLewis** [comment]
Needs to be enabled on extloadwiki and then Parsoid needs to work on private wikis first. I'll do that now.

**Comment by JohnFLewis** [comment]
It seems fine. No direct comment on stability yet because literally no data. Going to enable on spiral.wiki per @quimgil requesting it first.

**Comment by JohnFLewis** [comment]
Theoretically this is done and any issues that arise would be out of scope of this per se so... closed :)
