### ISSUE TITLE
Install various extensions

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#69]
Perhaps we don't need all of them, perhaps we do.
- [ ] ApiSandbox - Declined (will be enabled on request only).
- [x] CategoryTree
- [x] CiteThisPage
- [x] Disambiguator
- [x] GlobalCssJs
- [ ] Graph - Declined. - Declined (will be enabled on request only).
- [ ] ImageMap - Declined (will be enabled on request only).
- [x] OAuth (John will take this one)
- [ ] Poem - Declined (will be enabled on request only).
- [ ] Popups - Declined (will be enabled on request only).
- [ ] RandomRootPage - Declined (will be enabled on request only).
- [ ] SyntaxHighlight - Declined (will be enabled on request only).
- [ ] WikiHiero - Declined (will be enabled on request only).

**Comment by JohnFLewis** [comment]
All look good I guess. I'll take OAuth though.

**Comment by Southparkfan** [comment]
Edited.

**Comment by JohnFLewis** [comment]
Done OAuth.

**Comment by NDKilla** [comment]
GlobalCssJs would be nice, also maybe CategoryTree

Assuming you're talking globally, I'm not sure others are needed. If you're talking just downloading and having enabling, why not all?

**Comment by quimgil** [comment]
Enabling extensions before having specific use cases for them sounds like a recipe for a failure, or at least for a lot of extra work for no known reason. Why?

Be careful not to follow Orain's steps too close.

**Comment by JohnFLewis** [comment]
I do agree with Quim a bit actually. OAuth and APISandbox would be focused on adding tools for developers or ones whom are interested. GlobalCssJs speaks for itself and would be helpful in general for everyone. The rest seem to be 'ones people would only use on a request' so probably should be avoided if possible/no use case exists.

**Comment by Southparkfan** [comment]
As I said in the comment, we likely don't need all of them - I just crafted a list from mediawiki.org's extensions, so I can see 'this one and that one should be enabled globally, that one only per-wiki and that one not at all'.

Please don't think I want to enable them all and enable them globally. That is not my goal.

**Comment by NDKilla** [comment]
Okay.. Well now that that was settled.. I'd still like GlobalCssJs and I'd like CatTree on quantixwiki

otherwise up to you guys

**Comment by Reception123** [comment]
I tried to install some but failed..

**Comment by Southparkfan** [comment]
CategoryTree, CiteThisPage and Disambiguator are now installed (and enabled globally) since these are quite simple, not complex, and they only add features; they don't change the way of how various things work. During testing they worked out-of-the-box for me, so I don't expect any major issues.

ImageMap, Poem, RandomRootPage and WikiHiero also seem simple to install (and, they again don't change things - they just add features), but I first want to wait a bit. Others are TBD. ApiSandbox and Graph are marked as not done for now.

**Comment by Reception123** [comment]
Please cross ImageMap and GlobalCssJs off of the list

**Comment by Southparkfan** [comment]
@Reception123: Only if they are actually enabled too.

**Comment by Southparkfan** [comment]
GlobalCssJs is done.

**Comment by JohnFLewis** [comment]
Status?

**Comment by Southparkfan** [comment]
It's okay as-is. Closing.
