### ISSUE TITLE
Account creation error

### ISSUE THREAD

**Issue by Wynter** [miraheze/mw-config#72]
I'm trying to create an account on Miraheze Meta, but I keep getting the following error:

(Cannot access the database: Unknown database 'delete3wiki' (185.52.1.77))

**Comment by Reception123** [comment]
Are you sure you went on https://meta.miraheze.org ? I am not sure what this error could be. Please try again.

**Comment by Reception123** [comment]
@Southparkfan @JohnFLewis I can confirm that account creation fails for me as well. Log in works.

**Comment by Southparkfan** [comment]
Looks like someone deleted delete3wiki, but forgot to remove it from the dblist. Fixed.
