### ISSUE TITLE
Create mwdeployconf script

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#76]
This script should check the PHP syntax of the MediaWiki config, and preferably a check for "curl -H "Host: meta.miraheze.org" 'http://127.0.0.1/wiki/Main_Page'" (if that request doesn't end with a 200 HTTP status code, things went wrong).

**Comment by JohnFLewis** [comment]
I don't understand the point of this if we deploy through puppet - unless you want to move to a manual deploy scheme?

**Comment by Southparkfan** [comment]
Who knows. I still don't know what the best way of ((non-)automatically) deploying changes would be.
Need to look at that.

**Comment by Southparkfan** [comment]
Meh.
