### ISSUE TITLE
Change Translate to REL1_25

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#84]
We're currently using Translate's master branch because https://gerrit.wikimedia.org/r/#/c/205728/ is not merged yet. If that is merged, we should change Translate's branch to REL1_25.

**Comment by quimgil** [comment]
A new MediaWiki Language Extension Bundle has been just released, and 1.25.x support is included: https://lists.wikimedia.org/pipermail/wikitech-l/2015-August/082967.html
The maintainers support the bundle, not the Translate extension alone. I would consider installing the bundle in Miraheze.

**Comment by JohnFLewis** [comment]
Done.
