### ISSUE TITLE
TemplateData: Mysteriously missing system message?

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#87]
When testing TemplateData before prod deployment, I noticed something strange - a mysteriously missing message:
Message exists in en.json:
```
root@mw1:/srv/mediawiki/w# cat extensions/TemplateData/i18n/en.json | grep "templatedata-modal-table-param-deprecatedValue"
        "templatedata-modal-table-param-deprecatedValue": "Deprecated guidance",
```
And eval.php says it's in the LC cache:
```
> echo wfMessage( 'templatedata-modal-table-param-deprecatedValue' )->plain();
Deprecated guidance
```

However, https://gyazo.com/f8f0fe87d6acbb6584a43c456506cc7f shows something like a missing message. I need to look at that.

**Comment by JohnFLewis** [comment]
Does this still exist? Can't confirm.
