### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Wynter** [miraheze/mw-config#96]
I'm getting this error whenever I try to access https://meta.miraheze.org/wiki/ or any subdomain of miraheze.org.

**Comment by Reception123** [comment]
Have also e-mailed John and Southparkfan. @JohnFLewis @Southparkfan

**Comment by Southparkfan** [comment]
Restarted HHVM. I will check asap why this happened when I have more time.

**Comment by elliotolds** [comment]
Did restarting initially fix the issue? I'm still getting "502 Bad Gateway" 2 hours after this was closed.

**Comment by Southparkfan** [comment]
It happened again.. I reverted a change I performed yesterday, and I hope to fixes the issue. Please do not hesitate to email sysadmin[at]miraheze[dot]org if the site is down.
