### ISSUE TITLE
Look at using CDB for dblists.

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/mw-config#97]
I'm planning to use a MariaDB database and https://www.mediawiki.org/wiki/CDB for v2 of dblists.

/srv/mediawiki/dblist/wikis.cdb will be a CDB file with the wikis and their settings (language, sitename, yes/not private, hasVisualEditor, etc). A maintenance script called /srv/mediawiki/w/maintenance/MirahezeMagic/rebuildWikisCDB.php will lookup the content of the MariaDB database, and rebuild the wikis.cdb file with the new content.

Then LocalSettings.php will read the wikis.cdb file, fetch the content, set the appropriate variables (such as $wgLanguageCode), and do whatever is needed to serve the page.

**Comment by JohnFLewis** [comment]
Are we still planning this approach or not?

**Comment by Southparkfan** [comment]
Nope.
